### ISSUE TITLE
zoomstack_roads_local crashes kernel

### ISSUE THREAD

**Issue by Ilkka-LBL** [OrdnanceSurvey/osdatahub#99]
I have an issue where my below code works perfectly fine when I do not include `zoomstack_roads_local` in the list of products (in _load_roads method). However, the code crashes IPython kernel if I include it and won't run in a standalone script either. I have tried reducing the query limit to 50, but this keeps happening, so I don't think it's a throttling issue. I also tried changing the name to `Zoomstack_RoadsLocal`, but to no avail. I don't really understand the issue and VSCode's debugger was not helpful either. 

```
def _call_features_api(self, product, extent):
        # Make the query to FeaturesAPI
        features = FeaturesAPI(self.os_key, product, extent)
        results = features.query(limit=5000)
        return results
    
def _download_products(self):
    for ward_cd, ward_nm in list(zip(self.wards['WD22CD'], self.wards['WD22NM'])):
        extent = Extent.from_ons_code(ward_cd)
        self._load_rails(extent, ward_nm)
        self._load_roads(extent, ward_nm)
        self._load_greenspaces(extent, ward_nm)
    
  def _load_roads(self, geo_extent, geo_name):
      # Download road lines by ward and reproject to UK standard:
      for product in ["zoomstack_roads_local", "zoomstack_roads_national", "zoomstack_roads_regional"]:
          file_save_path = Path('./Data/roads/').joinpath(f"{geo_name}_{product}.geojson")
          poly = reproject(geo_extent.polygon)
          if product == "zoomstack_roads_national":
              geo_extent = poly.buffer(10).simplify(10)
              geo_extent = Extent(poly, 'EPSG:27700')
          else:
              geo_extent = Extent(poly, 'EPSG:27700')
          if file_save_path.exists():
              print(f"{geo_name}_{product} downloaded already, moving on...")
              continue
          else:
              results = self._call_features_api(product, geo_extent)
              geojson.dump(results, open(file_save_path.as_posix(), "w"))
```

The specific error message I get from IPython: 

```
info 16:02:39.052: Dispose Kernel process 6748.
error 16:02:39.052: Raw kernel process exited code: 3221225477
error 16:02:39.053: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:2:33213)
	at c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:2:52265
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:2:52250)
	at y.dispose (c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:2:45732)
	at c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:139244
	at Z (c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:2:1608939)
	at Kp.dispose (c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:139221)
	at qp.dispose (c:\Users\isipila\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:146518)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 16:02:39.053: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 16:02:39.054: Cancel all remaining cells true || Error || undefined
```

**Comment by Ilkka-LBL** [comment]
Never mind, I figured out the issue was with the location of `poly = reproject(geo_extent.polygon)`. It needed to be placed before the for loop in the `_load_roads` method.
